# Installs and builds the package (including native modules)
# Using the image: balenalib/raspberrypi3-alpine-node:16
name: Build - Raspberry Pi 3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install ARM64 binfmt
        run: docker run --privileged --rm tonistiigi/binfmt --install arm
      - name: Build for Raspberry Pi 3
        run: docker build --platform linux/arm/v7 --file Dockerfile --tag raspberry-pi-3:$(date +%s) .
